name: end2end-tests

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.13', '1.22.7', '1.23.1' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v

      - name: Run Tests
        run: |
          e2e_failed=false
          
          for test_file in e2e/test_files/*_test; do
            output_file="./e2e/$(basename "${test_file/_test/_output}")"
          
            ./GO4SQL -file "$test_file" > "$output_file"
          
            expected_output="e2e/expected_outputs/$(basename "${test_file/_test/_expected_output}")"
          
            diff "$output_file" "$expected_output"
          
            if [ $? -ne 0 ]; then
              echo "E2E test for: {$test_file} failed"
              e2e_failed=true
            fi
          
            rm "./$output_file"
          done
          
          if [ "$e2e_failed" = true ]; then
            echo "E2E tests failed."
            exit 1
          else
            echo "All E2E tests passed."
          fi
