name: end2end-tests

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.13', '1.22.7', '1.23.1' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v

      - name: Run Tests
        run: |
          for test_file in e2e/test_files/*_test; do

            # Generate the output file path by replacing '_test' with '_output'
            output_file="${test_file/_test/_output}"

            # Run the test and redirect output
            ./GO4SQL -file "$test_file" > "$output_file"

            # Generate the expected output file path
            expected_output="e2e/expected_outputs/$(basename "$output_file")"

            # Perform the diff check
            diff "$output_file" "$expected_output"

            # Clean up the generated output file
            rm "$output_file"
          done
